export type Language = 'zh' | 'en'

export const COPY = {
  zh: {
    clubName: '碳基会所', openClub: '打开碳基会所', collapseClub: '收起碳基会所', switchLanguage: 'Switch to English', roomsLabel: '房间',
    agentRunning: 'Agent 正在工作 · 人类可以喘口气', agentIdle: 'Agent 当前空闲 · 缓冲区仍可围观',
    localIdentity: 'DSH 本机身份', lastSession: '上次', noCompletedSession: '暂无已完成会话', uploadAvatar: '上传头像', changeAvatar: '更换', uploadAvatarTitle: '上传或更换本机头像', yourAvatar: '你的头像', roomDemo: '席位状态 · 本地演示', roomLive: '席位状态 · 联网验签', shareLastSession: '自愿公开“上一个完成会话名”（默认不公开）', blockedCount: (count: number) => `已在本机屏蔽 ${count} 个身份`, clearBlocked: '全部取消',
    nodeOnline: (peers: number) => `P2P 节点在线 · ${peers} 个连接`, nodeStarting: 'P2P 节点启动中', nodeError: 'P2P 节点不可用', peerId: '节点身份', peerPending: '生成中', createInvite: '生成邀请', creatingInvite: '生成中…', inviteCode: '邀请口令', copy: '复制', copied: '已复制', pasteInvite: '粘贴对方的 carbon1 邀请口令', connectPeer: '加入', connecting: '连接中…', networkNote: (peers: number, bootstrap: number, relay: number) => `近场发现 ${peers} · 社区入口 ${bootstrap} · 中继预约 ${relay} · 自动重连已启用`,
    speakers: '发言席', seatUnit: '席', seatOpen: (index: number) => `第 ${index} 席开放`, seatWaiting: '等待候位者接席', seatActive: (index: number) => `第 ${index} 席 · 发言中`, seatWarning: '即将递补', departedMember: '已离开的旅客', lastTaskTitle: (title: string) => `上一个完成任务：${title}`,
    queueTitle: '候位区 · 先来后到', seatedSelf: '你正在发言席', seatedSelfHint: '不发言 2 分钟后自动让席', offerSelf: '轮到你接席', offerSeconds: (seconds: number) => `${seconds} 秒内确认`, queuePosition: (position: number) => `候位第 ${position} 位`, queuePositionHint: '可随时退出队列，围观不受影响', audienceCount: (count: number) => `${count} 人围观`, audienceHint: '排队不影响 Agent 继续工作', leaveQueue: '退出候位', joinQueue: '排队发言',
    offerSeat: (index: number) => `第 ${index} 席正在等你`, seconds: (seconds: number) => `${seconds} 秒`, acceptMic: '接过话筒', skipTurn: '这轮跳过', meshChat: '联网实况', signedEvents: (count: number) => `${count} 条已验签消息`, meshEmpty: '还没有联网消息；直连另一节点后，双方发言会出现在这里。', signedBy: '身份签名', profileSelfReported: '昵称与备注由本人自述', blockPeer: '本地屏蔽', copyEvidence: '复制证据', evidenceCopied: '验签证据已复制', hallChat: '候车室样例', demoConversation: '本机演示内容', audienceReactions: '围观者只显示反应', lockedRoom: '这是后续房型预告。', p2pComing: '公开社区测试版暂只开放大厅。', seatedPlaceholder: '说点什么，别把 Agent 的上下文拖进来…', audiencePlaceholder: '围观中；排到发言席后可输入', send: '发送', zeroModel: '0 次模型调用 · 消息不进入 Agent 上下文',
    errors: { 'not-seated': '围观状态不能发言，先排队接席。', empty: '写点什么再发送。', 'too-long': '单条最多 400 字。', 'slow-mode': '大厅是 8 秒慢速模式。', 'consecutive-limit': '连续两条后，先把话筒交给别人。' },
    networkErrors: { HALL_NOT_JOINED: '请先排队，获得发言席后再开口。', HALL_NOT_SEATED: '还在候位队列中，暂时不能发言。', HALL_PROFILE_SYNC: '身份资料正在同步，请稍后再试。', HALL_RATE_LIMIT: '发言过快或已连续两条，请把话筒留给别人。' },
    avatarErrors: { type: '请选择 JPG、PNG 或 WebP 图片。', size: '头像文件不能超过 5 MB。', compressed: '头像压缩后仍过大，请换一张更简单的图片。', read: '图片读取失败，请换一张试试。', decode: '无法识别这张图片。', canvas: '当前浏览器无法处理头像。', unknown: '头像处理失败。' },
  },
  en: {
    clubName: 'Carbon Club', openClub: 'Open Carbon Club', collapseClub: 'Collapse Carbon Club', switchLanguage: '切换到中文', roomsLabel: 'Rooms',
    agentRunning: 'Agent at work · humans can take a breather', agentIdle: 'Agent idle · the club stays open',
    localIdentity: 'Local DSH identity', lastSession: 'Last', noCompletedSession: 'No completed session yet', uploadAvatar: 'Upload avatar', changeAvatar: 'Change', uploadAvatarTitle: 'Upload or change local avatar', yourAvatar: 'Your avatar', roomDemo: 'Seat state · Local demo', roomLive: 'Seats · Signed mesh state', shareLastSession: 'Share last completed session name (off by default)', blockedCount: (count: number) => `${count} identity(s) hidden locally`, clearBlocked: 'Clear all',
    nodeOnline: (peers: number) => `P2P node online · ${peers} connection(s)`, nodeStarting: 'P2P node starting', nodeError: 'P2P node unavailable', peerId: 'Peer ID', peerPending: 'Generating', createInvite: 'Create invite', creatingInvite: 'Creating…', inviteCode: 'Invite code', copy: 'Copy', copied: 'Copied', pasteInvite: 'Paste the other peer’s carbon1 invite', connectPeer: 'Join', connecting: 'Connecting…', networkNote: (peers: number, bootstrap: number, relay: number) => `Nearby ${peers} · community entry ${bootstrap} · relay reservation ${relay} · auto-reconnect on`,
    speakers: 'Speaking seats', seatUnit: 'seats', seatOpen: (index: number) => `Seat ${index} open`, seatWaiting: 'Waiting for the next person', seatActive: (index: number) => `Seat ${index} · Speaking`, seatWarning: 'Rotating soon', departedMember: 'Departed traveller', lastTaskTitle: (title: string) => `Last completed task: ${title}`,
    queueTitle: 'Queue · First come, first served', seatedSelf: 'You have a speaking seat', seatedSelfHint: 'Two idle minutes releases it', offerSelf: 'A seat is ready for you', offerSeconds: (seconds: number) => `Confirm within ${seconds}s`, queuePosition: (position: number) => `Queue position ${position}`, queuePositionHint: 'Leave anytime without stopping your view', audienceCount: (count: number) => `${count} watching`, audienceHint: 'Queuing does not interrupt your Agent', leaveQueue: 'Leave queue', joinQueue: 'Join queue',
    offerSeat: (index: number) => `Seat ${index} is waiting for you`, seconds: (seconds: number) => `${seconds}s`, acceptMic: 'Take the mic', skipTurn: 'Skip this turn', meshChat: 'Live mesh', signedEvents: (count: number) => `${count} verified message(s)`, meshEmpty: 'No network messages yet. Connect another peer and signed posts will appear here.', signedBy: 'Identity signed', profileSelfReported: 'name and note are self-reported', blockPeer: 'Hide locally', copyEvidence: 'Copy evidence', evidenceCopied: 'Verified evidence copied', hallChat: 'Waiting-room sample', demoConversation: 'Local demo content', audienceReactions: 'Audience reactions only', lockedRoom: 'This room type is a roadmap preview.', p2pComing: 'The public community beta currently enables the lobby only.', seatedPlaceholder: 'Say something—Agent context stays out of here…', audiencePlaceholder: 'Watching; input opens when you get a seat', send: 'Send', zeroModel: '0 model calls · Messages never enter Agent context',
    errors: { 'not-seated': 'Audience members cannot post. Join the queue first.', empty: 'Write something before sending.', 'too-long': 'Messages are limited to 400 characters.', 'slow-mode': 'The lobby uses an 8-second slow mode.', 'consecutive-limit': 'After two messages, hand the mic to someone else.' },
    networkErrors: { HALL_NOT_JOINED: 'Join the queue before speaking.', HALL_NOT_SEATED: 'You are still in the queue and do not have a speaking seat yet.', HALL_PROFILE_SYNC: 'Your profile is still syncing. Try again shortly.', HALL_RATE_LIMIT: 'You are posting too quickly or have sent two in a row. Give someone else the mic.' },
    avatarErrors: { type: 'Choose a JPG, PNG, or WebP image.', size: 'Avatar files must be 5 MB or smaller.', compressed: 'The compressed avatar is still too large. Try a simpler image.', read: 'Could not read that image. Try another one.', decode: 'That image could not be decoded.', canvas: 'This browser cannot process avatars.', unknown: 'Avatar processing failed.' },
  },
} as const
